# Generated by Django 2.2 on 2020-06-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurmement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_d', models.DateField(blank=True, null=True)),
                ('datatime_h', models.TimeField(blank=True, null=True)),
                ('obrazec', models.CharField(blank=True, max_length=30, null=True)),
                ('sera', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('rasseyanoe', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('koncentracia', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('analprog', models.CharField(blank=True, max_length=30, null=True)),
                ('operator', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'measurmement',
                'managed': False,
            },
        ),
    ]
